"""Generate analysis.ipynb — interactive expenditure analysis notebook.

One-shot generator. Run: python make_notebook.py  ->  writes analysis.ipynb
Edit the notebook directly afterwards; rerun only to rebuild from scratch.

Sections
--------
 1  Overview (totals, biggest month, biggest category)
 2  Monthly Trend + 3-month rolling avg
 3  Cumulative Net
 4  Spend by Category per Year (RM stacked + % share)
 5  Category Trends Over Time (top-8 monthly lines)
 6  Expense Breakdown — Sunburst
 7  Income Breakdown — Sunburst
 8  Account-Level Spend
 9  Year-over-Year Monthly Comparison
10  Recurring vs One-Off Breakdown
11  Other Audit + Note-pattern frequency table
12  Top 20 Biggest Transactions
13  Day-of-Week Spend Pattern
14  Data Quality Report
"""
import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []
md   = lambda s: cells.append(nbf.v4.new_markdown_cell(s))
code = lambda s: cells.append(nbf.v4.new_code_cell(s))

# ── Title ──────────────────────────────────────────────────────────────────
md("""\
# Income & Expenditure Analysis

Interactive analysis of Money Manager data (2022–2026). Charts are Plotly —
hover for values, zoom, toggle legend entries, drill into the sunbursts.

**Data:** `data/MasterFile.csv` (generated by `build_master.py`).
`EntryType == "Normal"` excludes transfers & balance adjustments — all spend/
income figures below use Normal entries only.

**Sections:** Overview · Monthly Trend · Cumulative Net · Category Spend \
· Category Trends · Expense Sunburst · Income Sunburst · Account Spend \
· Year-over-Year · Recurring vs One-Off · Other Audit · Top 20 · Day-of-Week \
· Data Quality\
""")

# ── Imports & data load ────────────────────────────────────────────────────
code("""\
import calendar
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from itables import init_notebook_mode, show as ishow

init_notebook_mode(all_interactive=False)  # opt-in per table via ishow()
pd.options.display.float_format = lambda x: f"{x:,.2f}"

df = pd.read_csv("data/MasterFile.csv", encoding="utf-8-sig", parse_dates=["Date"])
df["YearMonth"] = df["Date"].dt.to_period("M").dt.to_timestamp()

normal = df[df["EntryType"] == "Normal"].copy()
exp = normal[normal["Income/Expense"] == "Expense"].copy()
inc = normal[normal["Income/Expense"] == "Income"].copy()

print(f"{len(df):,} total rows | {len(normal):,} normal | "
      f"{df['Date'].min():%Y-%m-%d} -> {df['Date'].max():%Y-%m-%d}")""")

# ── 1. Overview ────────────────────────────────────────────────────────────
md("## 1. Overview")

code("""\
total_exp = exp["MYR"].sum()
total_inc = inc["MYR"].sum()
net       = total_inc - total_exp
months    = df["YearMonth"].nunique()

m_exp_ser      = exp.groupby("YearMonth")["MYR"].sum()
biggest_mo_dt  = m_exp_ser.idxmax()
biggest_mo_val = m_exp_ser.max()

cat_ser       = exp.groupby("Category")["MYR"].sum()
biggest_cat   = cat_ser.idxmax()
biggest_cat_v = cat_ser.max()

print(f"Total income:    RM {total_inc:>10,.0f}")
print(f"Total expense:   RM {total_exp:>10,.0f}")
print(f"Net:             RM {net:>10,.0f}")
print(f"Savings rate:    {net/total_inc*100:>9.1f}%")
print(f"Avg spend/mo:    RM {total_exp/months:>10,.0f}  (over {months} months)")
print(f"Avg income/mo:   RM {total_inc/months:>10,.0f}")
print(f"Biggest mo:      {biggest_mo_dt:%Y-%m}  RM {biggest_mo_val:,.0f}")
print(f"Biggest cat:     {biggest_cat}  RM {biggest_cat_v:,.0f}"
      f"  ({biggest_cat_v/total_exp*100:.1f}% of spend)")""")

# ── 2. Monthly Trend ───────────────────────────────────────────────────────
md("""\
## 2. Monthly Trend — Income, Expense, Net

Faint lines = raw monthly. Bold lines = 3-month rolling average (smooths noise).
Hover for exact RM; toggle series via legend.\
""")

code("""\
m_exp = exp.groupby("YearMonth")["MYR"].sum().rename("Expense")
m_inc = inc.groupby("YearMonth")["MYR"].sum().rename("Income")
trend = pd.concat([m_inc, m_exp], axis=1).fillna(0)
trend["Net"]         = trend["Income"] - trend["Expense"]
trend["Expense_3mo"] = trend["Expense"].rolling(3, min_periods=1).mean()
trend["Income_3mo"]  = trend["Income"].rolling(3, min_periods=1).mean()
trend = trend.reset_index()

fig = go.Figure()
for col, colour in [("Income", "seagreen"), ("Expense", "indianred"), ("Net", "royalblue")]:
    fig.add_scatter(x=trend["YearMonth"], y=trend[col], name=col,
                    mode="lines+markers", line=dict(color=colour, width=1),
                    opacity=0.35, legendgroup=col)
for col, avg_col, colour in [("Income",  "Income_3mo",  "seagreen"),
                               ("Expense", "Expense_3mo", "crimson")]:
    fig.add_scatter(x=trend["YearMonth"], y=trend[avg_col],
                    name=f"{col} 3mo avg", mode="lines",
                    line=dict(color=colour, width=2.5), legendgroup=col)

fig.update_layout(hovermode="x unified", yaxis_title="RM", xaxis_title="",
                  title="Monthly Income / Expense / Net + 3-Month Rolling Avg (RM)")
fig.add_hline(y=0, line_dash="dot", line_color="gray")
fig.show()""")

# ── 3. Cumulative Net ──────────────────────────────────────────────────────
md("""\
## 3. Cumulative Net

Running total of (income − expense) since the first recorded month.
Bars = monthly net (green surplus / red deficit); line = cumulative position.\
""")

code("""\
trend2 = trend.copy()
trend2["Cumulative Net"] = trend2["Net"].cumsum()
bar_colours = ["seagreen" if v >= 0 else "indianred" for v in trend2["Net"]]

fig = go.Figure()
fig.add_bar(x=trend2["YearMonth"], y=trend2["Net"], name="Monthly Net",
            marker_color=bar_colours, opacity=0.6)
fig.add_scatter(x=trend2["YearMonth"], y=trend2["Cumulative Net"],
                name="Cumulative Net", mode="lines+markers",
                line=dict(color="royalblue", width=2.5))
fig.update_layout(title="Cumulative Net Savings (RM)", hovermode="x unified",
                  yaxis_title="RM", xaxis_title="")
fig.add_hline(y=0, line_dash="dot", line_color="gray")
fig.show()""")

# ── 4. Spend by Category per Year ─────────────────────────────────────────
md("""\
## 4. Spend by Category, per Year

**Top:** absolute RM. **Bottom:** % share of that year's total spend.
Click a category in the legend to hide/isolate it.\
""")

code("""\
cat_year = (exp.groupby(["Year", "Category"])["MYR"].sum()
              .reset_index().sort_values("MYR", ascending=False))

fig = px.bar(cat_year, x="Year", y="MYR", color="Category",
             title="Annual Spend by Category — RM (stacked)")
fig.update_layout(barmode="stack", yaxis_title="RM")
fig.show()

cat_year_pct = cat_year.copy()
cat_year_pct["Pct"] = (cat_year["MYR"]
                       / cat_year.groupby("Year")["MYR"].transform("sum") * 100)
fig2 = px.bar(cat_year_pct, x="Year", y="Pct", color="Category",
              title="Annual Spend by Category — % Share")
fig2.update_layout(barmode="stack", yaxis_title="%", yaxis_range=[0, 100])
fig2.show()""")

# ── 5. Category Trends Over Time ───────────────────────────────────────────
md("""\
## 5. Category Trends Over Time

Monthly spend for the top 8 categories by total RM.
Shows which categories are growing or shrinking over the years.
Toggle categories via legend to isolate any one.\
""")

code("""\
top_cats  = exp.groupby("Category")["MYR"].sum().nlargest(8).index.tolist()
cat_trend = (exp[exp["Category"].isin(top_cats)]
               .groupby(["YearMonth", "Category"])["MYR"].sum()
               .reset_index())
fig = px.line(cat_trend, x="YearMonth", y="MYR", color="Category",
              markers=True, title="Monthly Spend — Top 8 Categories (RM)")
fig.update_layout(hovermode="x unified", yaxis_title="RM", xaxis_title="")
fig.show()""")

# ── 6. Expense Sunburst ────────────────────────────────────────────────────
md("""\
## 6. Expense Breakdown — Sunburst

Click a category to drill into its subcategories; click the centre to zoom out.\
""")

code("""\
sb = exp.copy()
sb["Subcategory"] = sb["Subcategory"].fillna("(none)").replace("", "(none)")
fig = px.sunburst(sb, path=["Category", "Subcategory"], values="MYR",
                  title="Expense: Category → Subcategory (RM)")
fig.update_traces(textinfo="label+percent entry")
fig.show()""")

# ── 7. Income Sunburst ─────────────────────────────────────────────────────
md("""\
## 7. Income Breakdown — Sunburst

Where does income come from? Drill-down from source category to subcategory.\
""")

code("""\
inc_sb = inc.copy()
inc_sb["Subcategory"] = inc_sb["Subcategory"].fillna("(none)").replace("", "(none)")
fig = px.sunburst(inc_sb, path=["Category", "Subcategory"], values="MYR",
                  title="Income: Category → Subcategory (RM)")
fig.update_traces(textinfo="label+percent entry")
fig.show()""")

# ── 8. Account-Level Spend ─────────────────────────────────────────────────
md("""\
## 8. Account-Level Spend

Which account (Maybank, CIMB, Cash, etc.) was used the most per year?\
""")

code("""\
acc = (exp.groupby(["Account", "Year"])["MYR"].sum()
         .reset_index().sort_values("MYR", ascending=False))
fig = px.bar(acc, x="Account", y="MYR", color="Year", barmode="group",
             title="Spend by Account per Year (RM)")
fig.update_layout(yaxis_title="RM", xaxis_title="")
fig.show()""")

# ── 9. YoY Monthly Comparison ─────────────────────────────────────────────
md("""\
## 9. Year-over-Year Monthly Comparison

Heatmap: each cell = total expense for that (month, year) pair.
Reveals seasonality — consistently hot months show up across all years.\
""")

code("""\
yoy = exp.groupby(["Year", "Month"])["MYR"].sum().reset_index()
pivot_yoy = yoy.pivot(index="Month", columns="Year", values="MYR").fillna(0)
pivot_yoy.index = [calendar.month_abbr[m] for m in pivot_yoy.index]
fig = px.imshow(pivot_yoy, text_auto=".0f", aspect="auto",
                color_continuous_scale="Blues",
                title="Expense by Month × Year — YoY Comparison (RM)")
fig.update_layout(xaxis_title="Year", yaxis_title="")
fig.show()""")

# ── 10. Recurring vs One-Off ───────────────────────────────────────────────
md("""\
## 10. Recurring vs One-Off Breakdown

`RecurringFlag = True` when a (Category, Subcategory) combo appears in 3+ distinct
calendar months — identifies subscriptions, rent, habitual expense types.

**Top:** RM split recurring vs one-off per category.
**Bottom:** monthly recurring baseline vs variable spend.\
""")

code("""\
rec = exp.copy()
rec["Type"] = rec["RecurringFlag"].map({True: "Recurring", False: "One-Off"})

# RM by category split recurring/one-off
cat_rec = (rec.groupby(["Category", "Type"])["MYR"].sum()
              .reset_index().sort_values("MYR", ascending=False))
fig = px.bar(cat_rec, x="Category", y="MYR", color="Type",
             barmode="stack",
             color_discrete_map={"Recurring": "steelblue", "One-Off": "salmon"},
             title="Spend by Category — Recurring vs One-Off (RM)")
fig.update_layout(yaxis_title="RM", xaxis_title="")
fig.show()

# Monthly recurring baseline vs variable
mo_rec = (rec.groupby(["YearMonth", "Type"])["MYR"].sum()
             .reset_index())
fig2 = px.bar(mo_rec, x="YearMonth", y="MYR", color="Type",
              barmode="stack",
              color_discrete_map={"Recurring": "steelblue", "One-Off": "salmon"},
              title="Monthly Spend — Recurring Baseline vs Variable (RM)")
fig2.update_layout(yaxis_title="RM", xaxis_title="", hovermode="x unified")
fig2.show()

# Summary
r_total = rec[rec["RecurringFlag"]]["MYR"].sum()
o_total = rec[~rec["RecurringFlag"]]["MYR"].sum()
print(f"Recurring:  RM {r_total:>10,.0f}  ({r_total/(r_total+o_total)*100:.1f}%)")
print(f"One-Off:    RM {o_total:>10,.0f}  ({o_total/(r_total+o_total)*100:.1f}%)")""")

# ── 11. Other Audit ────────────────────────────────────────────────────────
md("""\
## 11. `Other` Audit

Transactions still in the catch-all `Other` category after auto-reclassification.
**Top table:** individual transactions sorted by RM.
**Bottom table:** top Note patterns — easiest candidates to add rules for in
`note_patterns.csv` (rerun `build_master.py` after adding).\
""")

code("""\
other = exp[exp["Category"] == "Other"][
    ["Date", "Account", "Subcategory", "Note", "MYR"]
].sort_values("MYR", ascending=False)
print(f"Remaining Other: RM {other['MYR'].sum():,.0f} across {len(other)} txns")
ishow(other, maxBytes=0)

note_freq = (other.groupby("Note")
               .agg(Count=("MYR", "count"), Total_MYR=("MYR", "sum"))
               .sort_values("Total_MYR", ascending=False)
               .head(30)
               .reset_index())
print("\\nTop Note patterns still in Other:")
ishow(note_freq, maxBytes=0)""")

# ── 12. Top 20 ─────────────────────────────────────────────────────────────
md("## 12. Top 20 Biggest Transactions")

code("""\
top = exp.nlargest(20, "MYR").copy()
top["label"] = top["Date"].dt.strftime("%Y-%m-%d") + " · " + top["Category"]
fig = px.bar(top.sort_values("MYR"), x="MYR", y="label", orientation="h",
             hover_data=["Account", "Subcategory", "Note"],
             title="Top 20 Single Expenses (RM)")
fig.update_layout(yaxis_title="", xaxis_title="RM", height=600)
fig.show()""")

# ── 13. Day-of-Week ────────────────────────────────────────────────────────
md("""\
## 13. Day-of-Week Spend Pattern

Heatmap of total spend by weekday across years — spot which days drain most.\
""")

code("""\
hm = exp.copy()
hm["Weekday"] = pd.Categorical(
    hm["Date"].dt.day_name(),
    categories=["Monday", "Tuesday", "Wednesday", "Thursday",
                "Friday", "Saturday", "Sunday"], ordered=True)
pivot = hm.pivot_table(index="Weekday", columns="Year", values="MYR",
                       aggfunc="sum", fill_value=0, observed=False)
fig = px.imshow(pivot, text_auto=".0f", aspect="auto",
                color_continuous_scale="Reds",
                title="Total Spend by Weekday and Year (RM)")
fig.update_layout(xaxis_title="Year", yaxis_title="")
fig.show()""")

# ── 14. Data Quality Report ────────────────────────────────────────────────
md("""\
## 14. Data Quality Report

Generated by `build_master.py` at each rebuild.
Shows blank subcategory %, blank note %, and spend spread per category.
High `BlankSubcatPct` = candidate for more granular classification in Money Manager.\
""")

code("""\
qr_path = Path("data/quality_report.csv")
if qr_path.exists():
    qr = pd.read_csv(qr_path, encoding="utf-8-sig")
    ishow(qr, maxBytes=0)

    fig = px.bar(qr, x="Category", y="BlankSubcatPct",
                 title="Blank Subcategory % by Category",
                 color="BlankSubcatPct", color_continuous_scale="Oranges")
    fig.update_layout(yaxis_title="%", xaxis_title="")
    fig.show()
else:
    print("data/quality_report.csv not found — run build_master.py to generate.")""")

# ── Write ──────────────────────────────────────────────────────────────────
nb["cells"] = cells
nb["metadata"] = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.14.5"},
}
with open("analysis.ipynb", "w", encoding="utf-8") as f:
    nbf.write(nb, f)
print(f"Wrote analysis.ipynb ({len(cells)} cells)")
